### ISSUE TITLE
Flask example not working.

### ISSUE THREAD

**Issue by YukSeungChan** [pylover/sqlalchemy-media#64]
Hello,

I ran flask exmaple app on python 3.5. but occurred below error.

```
Traceback (most recent call last):
  File "flask_sam.py", line 9, in <module>
    from sqlalchemy_media import Image, ImageValidator, ImageProcessor, WandAnalyzer, StoreManager, FileSystemStore
  File "/Users/loup/.pyenv/versions/sqlalchemy-media-flask-3.5.0/lib/python3.5/site-packages/sqlalchemy_media/__init__.py", line 2, in <module>
    from .typing_ import Attachable
  File "/Users/loup/.pyenv/versions/sqlalchemy-media-flask-3.5.0/lib/python3.5/site-packages/sqlalchemy_media/typing_.py", line 5, in <module>
    FileLike = Union[IO[BytesIO], BytesIO, FileIO]
  File "/Users/loup/.pyenv/versions/3.5.0/lib/python3.5/typing.py", line 979, in __getitem__
    (_type_repr(new), _type_repr(old), self))
TypeError: Cannot substitute _io.BytesIO for ~AnyStr in typing.IO[~AnyStr]
```

**Comment by pylover** [comment]
Here is working well, i cannot reproduce the error
Oh. please update your python to 3.5.2
or higher
python 3.6 just released as rc1
