### ISSUE TITLE
Occurred error when delete image that have thumbnails.

### ISSUE THREAD

**Issue by YukSeungChan** [pylover/sqlalchemy-media#68]
`code`

```
    with StoreManager(db.session, delete_orphan=True):
        with db.session.begin():
            item = Item.create(
                image=ItemImage.create_from(
                    'https://www.python.org/static/img/python-logo@2x.png'),
                type=ItemType.gifticon,
                name='test',
                price=100,
                is_sell=True
            )
            thumb = item.image.get_thumbnail(ratio=.3, auto_generate=True)
        with db.session.begin():
            db.session.delete(item)

```

`errors`

```
Traceback (most recent call last):
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 564, in __exit__
    self.commit()
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy_media/stores.py", line 458, in on_commit
    f.delete()
AttributeError: 'dict' object has no attribute 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 80, in <module>
    db.session.delete(item)
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 567, in __exit__
    self.rollback()
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.reraise(type_, value, traceback)
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 567, in __exit__
    self.rollback()
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 477, in rollback
    self._assert_active(prepared_ok=True, rollback_ok=True)
  File "/Users/loup/.pyenv/versions/momo-3.5.2/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 258, in _assert_active
    "This session is in 'committed' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
```

**Comment by YukSeungChan** [comment]
@pylover I just changed `get_objects_to_delete` function. then doesn't occur error. but didn't delete thumbnails.

```
def get_objects_to_delete(self):
        """
        Returns the files to be deleted, if the attachment is marked for deletion.

        """
        yield from super().get_objects_to_delete()
        for t in self.thumbnails:
            yield self.__thumbnail_type__(**t[3])
```

**Comment by pylover** [comment]
Thanks
