### ISSUE TITLE
Cannot handle deleted file on FilesystemStorage

### ISSUE THREAD

**Issue by meyt** [pylover/sqlalchemy-media#78]
Accidentally one of uploaded file deleted by myself, and there is problem occurred when i want to delete it from sqlalchemy-media:
```
2017-04-24 17:33:43,333 INFO sqlalchemy.engine.base.Engine COMMIT
Traceback (most recent call last):
  File "/.../product.py", line 106, in edit
    product_obj.update(product_id=[context.form['id']], **params)
  File "/.../product.py", line 222, in update
    self.db.commit()
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/.../sqlalchemy-media/sqlalchemy_media/stores.py", line 472, in on_commit
    f.delete()
  File "/.../sqlalchemy-media/sqlalchemy_media/attachments.py", line 274, in delete
    self.get_store().delete(self.path)
  File "/.../sqlalchemy-media/sqlalchemy_media/stores.py", line 133, in delete
    remove(self._get_physical_path(filename))
FileNotFoundError: [Errno 2] No such file or directory: '/.../upload/products/product-d5c28ba5-fa63-412a-bd53-f997fd051aff-Screenshot_2017-02-11_14-47-52.png'
```
After that i cannot connect to database again because this errors happen:
```
  File "/.../product.py", line 112, in edit
    db.get_session('db1').rollback()
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 838, in rollback
    self.transaction.rollback()
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 477, in rollback
    self._assert_active(prepared_ok=True, rollback_ok=True)
  File "/.../env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 258, in _assert_active
    "This session is in 'committed' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
```

**Comment by pylover** [comment]
What is your idea? what should we do when such situation happens?

**Comment by meyt** [comment]
I think this error can be ignored

**Comment by pylover** [comment]
Mmmmm, I think differently. This implicit behaviour may cause confusion both while debug and dployement.

**Comment by pylover** [comment]
I think it must raise an error, If any software, and or human is deleted the file from storage.

**Comment by pylover** [comment]
From the zen of python: `Explicit is better than implicit.`
