### ISSUE TITLE
Mock-up servers failing

### ISSUE THREAD

**Issue by pylover** [pylover/sqlalchemy-media#82]
@YukSeungChan, Sometimes the tests are failing, because the mockup server connections are refused.

Previously, I added some delays after the server startup: https://github.com/pylover/sqlalchemy-media/blob/master/sqlalchemy_media/tests/test_s3_store.py#L67

But the problem already exists.
Restarting the job is a temporary workaround.

this is the log from Travis:
```
$ coverage run --source sqlalchemy_media $(which nosetests)
............127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
....127.0.0.1 - - [26/May/2017 20:45:27] "GET / HTTP/1.1" 200 -
.....................127.0.0.1 - - [26/May/2017 20:45:30] "PUT /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] "GET /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] "DELETE /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] code 404, message NotFound
127.0.0.1 - - [26/May/2017 20:45:30] "GET /test_delete/sample_text_file1.txt HTTP/1.1" 404 -
.127.0.0.1 - - [26/May/2017 20:45:30] "PUT /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] "GET /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] code 400, message BadBucketError
127.0.0.1 - - [26/May/2017 20:45:30] "DELETE /test_delete/sample_text_file1.txt HTTP/1.1" 400 -
.127.0.0.1 - - [26/May/2017 20:45:30] "PUT /files/file-e1812a08-bcc4-4358-ba07-f9b44f925812.txt HTTP/1.1" 200 -
.127.0.0.1 - - [26/May/2017 20:45:30] "PUT /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] "GET /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:30] "GET /test_delete/sample_text_file1.txt HTTP/1.1" 200 -
.127.0.0.1 - - [26/May/2017 20:45:30] "PUT /test/files/file-436d0b6b-2fc2-4b43-bd48-64efe1645fa8.txt HTTP/1.1" 200 -
.127.0.0.1 - - [26/May/2017 20:45:31] "PUT /files/file-4ed9eb09-0814-42bb-ba8f-a710d099243d.txt HTTP/1.1" 200 -
.127.0.0.1 - - [26/May/2017 20:45:31] "PUT /files/file-ddc0f7f6-9521-427b-a5ab-b54c90f821d3.txt HTTP/1.1" 200 -
.127.0.0.1 - - [26/May/2017 20:45:31] code 400, message BadBucketError
127.0.0.1 - - [26/May/2017 20:45:31] "PUT /test_put_from_stream/file_from_stream1.txt HTTP/1.1" 400 -
.127.0.0.1 - - [26/May/2017 20:45:31] "PUT /test_put_from_stream/file_from_stream1.txt HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2017 20:45:31] "GET /test_put_from_stream/file_from_stream1.txt HTTP/1.1" 200 -
..Process Process-3:
Traceback (most recent call last):
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 47, in run_s3_server
    run_simple(TEST_HOST, TEST_PORT, mock_app, threaded=True)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/opt/python/3.5-dev/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
E.Process Process-5:
Traceback (most recent call last):
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 47, in run_s3_server
    run_simple(TEST_HOST, TEST_PORT, mock_app, threaded=True)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/opt/python/3.5-dev/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
E..Process Process-8:
Traceback (most recent call last):
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 47, in run_s3_server
    run_simple(TEST_HOST, TEST_PORT, mock_app, threaded=True)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/opt/python/3.5-dev/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
E.Process Process-10:
Traceback (most recent call last):
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python/3.5-dev/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 47, in run_s3_server
    run_simple(TEST_HOST, TEST_PORT, mock_app, threaded=True)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/opt/python/3.5-dev/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/python/3.5-dev/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
E.......
======================================================================
ERROR: test_delete_error (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 70, in setUp
    res = requests.put(TEST_SERVER_URL)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10002): Max retries exceeded with url: /test-bucket (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe8a8646160>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_open (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 70, in setUp
    res = requests.put(TEST_SERVER_URL)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10002): Max retries exceeded with url: /test-bucket (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe8a863def0>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_public_base_url_strip (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 70, in setUp
    res = requests.put(TEST_SERVER_URL)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10002): Max retries exceeded with url: /test-bucket (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe8a863d828>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_put_from_stream (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pylover/sqlalchemy-media/sqlalchemy_media/tests/test_s3_store.py", line 70, in setUp
    res = requests.put(TEST_SERVER_URL)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10002): Max retries exceeded with url: /test-bucket (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe8a86171d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 62 tests in 29.069s
FAILED (errors=4)
```

**Comment by YukSeungChan** [comment]
Okay I'll check it tomorrow :D

**Comment by pylover** [comment]
Thanks a lot. Don't worry. there is no time force in open source.

**Comment by YukSeungChan** [comment]
@pylover It's a difficult problem to solve... haha

**Comment by pylover** [comment]
lol

**Comment by pylover** [comment]
Yes because the behaviour is random

**Comment by pylover** [comment]
I think we need a mutex lock, for example, a PID file to ensure the server process(es) is/are started currently.

So the test cases can wait until this situation.

**Comment by pylover** [comment]
We need to do R&D about inter-process communication and locks. there are many methods are available, from simple text file to dbus messaging.

**Comment by YukSeungChan** [comment]
I don’t know why tests stop in the middle when I run them.

command: nosetests -v --with-coverage --cover-erase --cover-package=./sqlalchemy_media --
cover-html

**output**
```
test_magic (sqlalchemy_media.tests.test_analyzers.AnalyzerTestCase) ... ok
test_wand (sqlalchemy_media.tests.test_analyzers.AnalyzerTestCase) ... ok
test_attachment_list (sqlalchemy_media.tests.test_collections.CollectionsTestCase) ... ok
test_coerce (sqlalchemy_media.tests.test_collections.CollectionsTestCase) ... ok
test_file_dict (sqlalchemy_media.tests.test_collections.CollectionsTestCase) ... ok
test_delete_orphan (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
test_delete_orphan_dict (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
test_delete_orphan_dict_item (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
https://github.com/pylover/sqlalchemy-media/issues/81 ... ok
test_delete_orphan_list (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
test_delete_orphan_list_item (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
test_without_delete_orphan (sqlalchemy_media.tests.test_delete_orphan.DeleteOrphanTestCase) ... ok
test_cgi_field_storage (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_force_seekable (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_localfs (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_non_seekable (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_stream (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_url (sqlalchemy_media.tests.test_descriptors.AttachableDescriptorsTestCase) ... ok
test_attribute_type_assertion (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_attribute_type_coercion (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_content_type_validator (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_file (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_file_size_limit (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_model_constructor (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_overwrite (sqlalchemy_media.tests.test_file.FileTestCase) ... ok
test_delete (sqlalchemy_media.tests.test_filesystem_store.FileSystemStoreTestCase) ... ok
test_open (sqlalchemy_media.tests.test_filesystem_store.FileSystemStoreTestCase) ... ok
test_put_from_stream (sqlalchemy_media.tests.test_filesystem_store.FileSystemStoreTestCase) ... ok
test_is_uri (sqlalchemy_media.tests.test_helpers.HelpersTestCase) ... ok
test_image (sqlalchemy_media.tests.test_image.ImageTestCase) ... ok
test_image_list (sqlalchemy_media.tests.test_image.ImageTestCase) ... ok
Issue #72 ... ok
test_pre_process (sqlalchemy_media.tests.test_image.ImageTestCase) ... ok
test_thumbnail (sqlalchemy_media.tests.test_image.ImageTestCase) ... ok
test_thumbnail_delete (sqlalchemy_media.tests.test_image.ImageTestCase) ... ok
test_crop (sqlalchemy_media.tests.test_image_processors.ImageProcessorTestCase) ... ok
test_resize_reformat (sqlalchemy_media.tests.test_image_processors.ImageProcessorTestCase) ... ok
test_exception (sqlalchemy_media.tests.test_optionals.OptionalPackagesTestCase) ... ok
test_delete (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_delete_error (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_locate (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_open (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_prefix (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_public_base_url (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_public_base_url_strip (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_put_error (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_put_from_stream (sqlalchemy_media.tests.test_os2_store.OS2StoreTestCase) ... ok
test_delete (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_delete_error (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_locate (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_open (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_prefix (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_public_base_url (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_public_base_url_strip (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_put_error (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_put_from_stream (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_rrs_put (sqlalchemy_media.tests.test_s3_store.S3StoreTestCase) ... ok
test_context_stack (sqlalchemy_media.tests.test_store_manager.StoreContextTestCase) ... ok
test_default_store (sqlalchemy_media.tests.test_store_manager.StoreContextTestCase) ... ok
test_multithread (sqlalchemy_media.tests.test_store_manager.StoreContextTestCase) ... ok
test_unregister (sqlalchemy_media.tests.test_store_manager.StoreContextTestCase) ... ok
test_content_type_validator (sqlalchemy_media.tests.test_validators.ValidatorTestCase) ... ok
test_image_validator (sqlalchemy_media.tests.test_validators.ValidatorTestCase) ... ok


```

**Comment by pylover** [comment]
Yes, because this behaviour is random,

**Comment by pylover** [comment]
I guess the problem is found!

I'm going to use multithreading instead of multiprocessing to run the S3 mockup server.
I addition the `threading.Event` will be used to ensure the mockup server is up before running the tests.

**Comment by pylover** [comment]
@YukSeungChan, FYI: Hard coding the TCP port is not a good practice for mockup server.

The best approach is to pass the TCO port number zero `0`. and let the os choose a fresh port for us.

https://www.dnorth.net/2012/03/17/the-port-0-trick/

**Comment by pylover** [comment]
And please do not use abbreviations at all. for example: `server_p`

from the zen of python:

```
Special cases aren't special enough to break the rules.
```

**Comment by YukSeungChan** [comment]
Great ! Thanks
